config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('retail_network.urls', namespace='retail-network')),
    path('', include('employee.urls', namespace='employee'))
]

employee/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from employee.apps import EmployeeConfig

app_name = EmployeeConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='employee/login.html'), name='login'),  # вход в систему
    path('logout/', LogoutView.as_view(), name='logout'),  # выход из системы
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),  # получение токена для авторизации
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # обновление токена для авторизации
]

retail_network/urls.py
from django.urls import path

from retail_network.apps import RetailNetworkConfig
from retail_network.views import (RetailChainView, RetailChainDetailView, clear_debt, ContactsListView, LinkListAPIView,
                                LinkCreateAPIView, LinkRetrieveAPIView, LinkDestroyAPIView, LinkUpdateAPIView,
                                ContactCreateAPIView, ProductCreateAPIView)

app_name = RetailNetworkConfig.name

urlpatterns = [
    path('', RetailChainView.as_view(), name='retail-chain-list'),  # главная страница со списком всех звеньев сети
    path('link/<int:pk>', RetailChainDetailView.as_view(), name='retail-network'),  # звено сети детально
    path('clear-debt/<int:pk>', clear_debt, name='clear-debt'),  # очистка долга перед поставщиком
    path('city-list', ContactsListView.as_view(), name='city-list'),  # список городов
    path('<int:pk>', RetailChainView.as_view(), name='retail-chain-city'),  # фильтр звеньев сети по городу
    path('api/links', LinkListAPIView.as_view(), name='api-chain-list'),  # список звеньев сети через API
    path('api/links/create', LinkCreateAPIView.as_view(), name='api-chain-create'),  # создание звена сети через API
    path('api/links/<int:pk>', LinkRetrieveAPIView.as_view(), name='api-chain'),  # звено сети детально через API
    path('api/links/delete/<int:pk>', LinkDestroyAPIView.as_view(), name='api-chain-destroy'),  # удаление звена API
    path('api/links/update/<int:pk>', LinkUpdateAPIView.as_view(), name='api-chain-update'),  # обновление звена API
    path('api/contacts/create', ContactCreateAPIView.as_view(), name='api-contact-create'),  # добавление контактов
    path('api/product/create', ProductCreateAPIView.as_view(), name='api-product-create'),  # добавление продукта
]

retail_network/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}  # для необязательного поля


class Contacts(models.Model):
    """Модель контактов для звена сети по продаже электроники"""

    email = models.EmailField(verbose_name='Email')
    country = models.CharField(max_length=100, verbose_name='Страна')
    city = models.CharField(max_length=100, verbose_name='Город')
    street = models.CharField(max_length=100, verbose_name='Улица')
    home = models.IntegerField(verbose_name='Номер дома')

    def __str__(self):
        return f'{self.country}, {self.city}, {self.street}, {self.home}\n{self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Product(models.Model):
    """Модель продукта для сети по продаже электроники"""

    title = models.CharField(max_length=100, verbose_name='Название')
    product_model = models.CharField(max_length=255, verbose_name='Модель продукта')
    reliz_date = models.DateField(verbose_name='Дата выхода')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.title} {self.product_model}'


class Link(models.Model):
    """Модель звена сети по продаже электроники"""

    title = models.CharField(max_length=100, verbose_name='Название')  # Название звена
    contacts = models.ForeignKey(Contacts, verbose_name='Контакты', on_delete=models.CASCADE)  # Контакты звена
    products = models.ManyToManyField(Product, verbose_name='Продукты')  # Продукты
    supplier = models.ForeignKey('self',
                                 verbose_name='Поставщик',
                                 on_delete=models.SET_NULL,
                                 **NULLABLE)  # Поставщик
    debt = models.DecimalField(max_digits=10,
                               decimal_places=2,
                               verbose_name='Задолженность',
                               **NULLABLE)  # задолженность перед поставщиком
    created_at = models.DateTimeField(auto_now_add=True)  # дата/время создания

    class Meta:
        verbose_name = 'Звено'
        verbose_name_plural = 'Звенья'

    def __str__(self):
        return self.title

retail_network/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView
from rest_framework import generics, filters
from rest_framework.permissions import IsAuthenticated

from retail_network.models import Link, Contacts
from retail_network.serializers import LinkSerializer, ContactSerializer, ProductSerializer


class RetailChainView(ListView):
    """Класс-контроллер для отображения главной страницы"""

    model = Link  # Модель
    template_name = 'retail_network/retail_network.html'  # шаблон

    def get_queryset(self, *args, **kwargs):
        """Переопределение метода для формирования списка нужного списка звеньев сети"""

        queryset = []  # изначальный список

        # если пользователь авторизован
        if not self.request.user.is_anonymous:
            pk = self.kwargs.get('pk')  # проверяем есть ли в аргументах pk(ссылка на контакты)
            queryset = Link.objects.all()  # наполняем список звеньев сети

            # если в аргументах есть pk
            if pk:

                city = Contacts.objects.get(pk=pk).city  # по переданному pk находим город
                new_queryset = [link for link in queryset if link.contacts.city == city] # фильтруем список по городу
                queryset = new_queryset  # перезаписываем список звеньев сети

        return queryset


class RetailChainDetailView(LoginRequiredMixin, DetailView):
    """Контроллер для отображения страницы с информацией о звене сети"""
    model = Link  # модель
    template_name = 'retail_network/link_detail.html'  # шаблон


@login_required
def clear_debt(request, pk):
    """контроллер для обнуления задолженности перед поставщиком"""

    link = Link.objects.get(pk=pk)  # получаем нужное звено сети
    link.debt = 0  # обнуляем задолженность перед поставщиком
    link.save()  # сохраняем результат

    return redirect(reverse('retail-network:retail-chain-list'))  # перенаправляем на главную страницу


class ContactsListView(LoginRequiredMixin, ListView):
    """Контроллер для отображения списка городов"""

    model = Contacts  # Модель
    template_name = 'retail_network/contacts-list.html'  # шаблон

    def get_queryset(self):
        """переопределяем метод для создания списка контактов с уникальными городами"""

        contacts = Contacts.objects.all()  # список всех контактов
        queryset = []  # пустой список контактов
        cities = []  # пустой список городов

        for contact in contacts:

            # если города еще нет в списке
            if contact.city not in cities:
                cities.append(contact.city)  # добавляем город в список городов
                queryset.append(contact)  # добавляем контакты в список контактов

        return queryset


class LinkListAPIView(generics.ListAPIView):
    """Контроллер для просмотра списка звеньев сети через API"""

    serializer_class = LinkSerializer  # Сериализатор
    queryset = Link.objects.all()  # список звеньев сети

    permission_classes = [IsAuthenticated]  # разрешение на доступ авторизованным пользователям

    filter_backends = [filters.SearchFilter]  # фильтр
    search_fields = ['contacts__country']  # поле фильтрации по стране


class LinkCreateAPIView(generics.CreateAPIView):
    """Контроллер для создания звена сети"""

    serializer_class = LinkSerializer  # сериализатор
    permission_classes = [IsAuthenticated]  # разрешение на доступ авторизованным пользователям


class LinkRetrieveAPIView(generics.RetrieveAPIView):
    """Контроллер для просмотра звена сети"""

    serializer_class = LinkSerializer  # сериализатор
    queryset = Link.objects.all()  # список звеньев сети

    permission_classes = [IsAuthenticated]  # разрешение на доступ авторизованным пользователям


class LinkDestroyAPIView(generics.DestroyAPIView):
    """Контроллер для удаления звена сети"""

    queryset = Link.objects.all()  # список звеньев сети

    permission_classes = [IsAuthenticated]  # разрешение на доступ авторизованным пользователям


class LinkUpdateAPIView(generics.UpdateAPIView):
    """Контроллер для изменения звена сети"""

    serializer_class = LinkSerializer  # сериализатор
    queryset = Link.objects.all()  # список звеньев сети
    permission_classes = [IsAuthenticated]  # разрешение на доступ авторизованным пользователям

    def perform_update(self, serializer):
        """Удаляем поле debt из обновляемых данных"""

        debt = serializer.validated_data.pop('debt', None)  # удаление поля
        serializer.save()  # сохранение обновленных данных


class ContactCreateAPIView(generics.CreateAPIView):
    """Контроллер для создания контактов"""

    serializer_class = ContactSerializer  # сериализатор
    permission_classes = [IsAuthenticated]  # разрешение на доступ для авторизованных пользователей


class ProductCreateAPIView(generics.CreateAPIView):
    """Контроллер для создания продукта"""

    serializer_class = ProductSerializer  # Сериализатор
    permission_classes = [IsAuthenticated]

retail_network/templates/retail_network/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Network</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h3 class="my-0 mr-md-auto font-weight-normal">Network</h3>
    <h3 class="my-0 mr-md-auto font-weight-normal">{{ employee.name }}</h3>
    <h5 class="my-0 mr-md-auto font-weight-normal">Торговая сеть электроники</h5>
    <nav class="ms-6">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'retail-network:city-list' %}">Фильтр по городу</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'employee:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'employee:login' %}">Войти</a>
        {% endif %}

    </nav>
</div>
<body>
{% block content%}
{% endblock %}


<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

retail_network/templates/retail_network/contacts-list.html
{% extends 'retail_network/base.html'%}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Выберите город</h1>
</div>

<div class="container">
    {% for object in object_list %}
        <div class="row text-center">
            <p class="lead"><a class="text-muted" href="{% url 'retail-network:retail-chain-city' object.pk %}">{{ object.city }}</a></p>
        </div>
    {% endfor %}

</div>
{% endblock %}

retail_network/templates/retail_network/link_detail.html
{% extends 'retail_network/base.html'%}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.title }}</h1>
</div>

<div class="container">
    <div class="row text-center">
        <p class="lead">Контакты: {{ object.contacts }}</p>
    </div>

    <div class="row text-center">
        <p class="lead">Дата создания: {{ object.created_at }}</p>
    </div>

    <div class="row text-center">
        <p class="lead">Продукты: {{ object.products.all | join:"; " }}</p>
    </div>
    {% if object.supplier %}
        <div class="row text-center">
            <p class="lead">Поставщик: <a href="{% url 'retail-network:retail-network' object.supplier.pk %}">{{ object.supplier.title }}</a></p>
        </div>
        <div class="row text-center">
            <p class="lead">Задолженность перед поставщиком: {{ object.debt }} руб.</p>
        </div>
        <a href="{% url 'retail-network:clear-debt' object.pk %}" type="button" class="btn btn-lt btn-block btn-outline-danger">Очистить</a>
    {% endif %}

</div>
{% endblock %}

retail_network/templates/retail_network/retail_network.html
{% extends 'retail_network/base.html'%}

{% block content %}

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h5>Контакты:</h5>
                        <li> {{ object.contacts}}</li>
                        <h5>Продукты:</h5>
                        <li>{{ object.products.all | join:"&#10;" }}</li>
                        {% if object.supplier %}
                            <h5>Поставщик:</h5>
                            <a href="{% url 'retail-network:retail-network' object.supplier.pk %}">{{ object.supplier.title }}</a>
                            <h5>Задолженность:</h5>
                            <li>{{ object.debt }} руб</li>
                            <a href="{% url 'retail-network:clear-debt' object.pk %}" type="button" class="btn btn-lt btn-block btn-outline-danger">Очистить</a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}